default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: 127.0.0.1

development:
  <<: *default
  database: kalkomey_development

test:
  <<: *default
  database: kalkomey_test

production:
  <<: *default
  database: kalkomey_production
